// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneProject(arg1, arg2) {
  return window['go']['backend']['App']['CloneProject'](arg1, arg2);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['backend']['App']['DeleteProject'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function ListProjects() {
  return window['go']['backend']['App']['ListProjects']();
}

export function OpenFolder(arg1) {
  return window['go']['backend']['App']['OpenFolder'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['backend']['App']['OpenInVSCode'](arg1);
}

export function SetBaseDir(arg1) {
  return window['go']['backend']['App']['SetBaseDir'](arg1);
}
