// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CloneProject(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DeleteProject(arg1:string,arg2:boolean):Promise<void>;

export function GetConfig():Promise<backend.Config>;

export function ListProjects():Promise<Array<backend.Project>>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenInVSCode(arg1:string):Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function SetBaseDir(arg1:string):Promise<void>;
